language: generic
sudo: required
services:
  - docker

before_install:

  - docker build -t raj0909patel/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  raj0909patel/react-test npm test

after_success:
  - docker build -t raj0909patel/multi-client ./client
  - docker build -t raj0909patel/multi-nginx ./nginx
  - docker build -t raj0909patel/mulit-server ./server
  - docker build -t raj0909patel/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to Docker hub
  - docker push raj0909patel/multi-client
  - docker push raj0909patel/multi-nginx
  - docker push raj0909patel/multi-server
  - docker push raj0909patel/multi-worker
